### ISSUE TITLE
Attribute Error sometimes occurs when creating a PDF of a program

### ISSUE THREAD

**Issue by Daniel-Jang** [j-selby/CASS-Degrees-Code#251] opened 2019-08-25 09:10 UTC
While not all programs has this issue, the Bachelor of Arts sample program I created:
![image](https://user-images.githubusercontent.com/37033052/63647877-e9885e80-c76a-11e9-866a-5d5221672c3e.png)

caused this error when I clicked on the PDF button:
![image](https://user-images.githubusercontent.com/37033052/63647881-fad16b00-c76a-11e9-89ff-64ccf52311b1.png)

Specifically, the 'Subplan' rule causes issues as when I removed all subplan rules like such:
![image](https://user-images.githubusercontent.com/37033052/63647931-9236be00-c76b-11e9-8b34-9b4ff36c2710.png)

I got a generated PDF:
![image](https://user-images.githubusercontent.com/37033052/63647968-f9547280-c76b-11e9-9fb9-915e6b8ecbf9.png)

**Comment by j-selby** [comment] 2019-08-25 09:56
This was a regression caused by Github's double merge a while ago where it merged the pdf rules and the student rules pdfs together. This is fixed in #247

**Comment by Daniel-Jang** [comment] 2019-08-25 13:42
> This was a regression caused by Github's double merge a while ago where it merged the pdf rules and the student rules pdfs together. This is fixed in #247

Sorry, I should have had a look at that beforehand. I will check it out now.

**Comment by Daniel-Jang** [comment] 2019-08-26 05:24
(already resolved by another PR)

**Closed as completed** 2019-08-26 05:23 UTC
Labels: bug
