### ISSUE TITLE
Course list reports no course error if all courses in system added to list

### ISSUE THREAD

**Issue by j-selby** [j-selby/CASS-Degrees-Code#395] opened 2019-09-24 07:37 UTC
Lists currently exhibit an issue where course lists which contain at least one course can throw the no courses error if those courses were the only courses in the system.

Proposed fix would be to check if a list has >= 1 course added and not show that error.

**Comment by joshcbee** [comment] 2019-09-24 21:04
@j-selby is this what you are referencing? If so, it's an error message updating issue that should be addressed by #392. If you're talking about something different, can you post a screenshot? The bottom image is working as intended from what I can see.

![image](https://user-images.githubusercontent.com/10462891/65550246-899bf800-df62-11e9-9021-63cdddeb0ef4.png)


![image](https://user-images.githubusercontent.com/10462891/65550009-09759280-df62-11e9-92d9-bf5aad2c5165.png)

**Comment by JackSekoranja** [comment] 2019-09-29 13:13
Already fixed from previous PRs

**Closed as completed by JackSekoranja** 2019-09-29 13:13 UTC
Labels: bug, Difficulty: EASY
