### ISSUE TITLE
Make each rule to be more clearer to the user

### ISSUE THREAD

**Issue by Daniel-Jang** [j-selby/CASS-Degrees-Code#346] opened 2019-09-15 07:53 UTC
During UAT, the user was a bit confused on what each rule option did/meant, so perhaps make this a bit more clearer?

Perhaps add a small explanation for what each rule is in the drop down selection when adding rules? E.g.:
Before:
Course

After:
Course - List compulsory courses

UAT Document Link: https://docs.google.com/document/d/1wk9sX77a6Vi7mha6BX23KsZodu_yuyDUunoW9eJvKIs/edit#

**Comment by aidengeorge97** [comment] 2019-09-23 09:32
I think this is a duplicate of #317, they serve the same purpose but offer different suggestions. I'll link this suggestion to the original issue and close this as a duplicate.

**Closed as completed by aidengeorge97** 2019-09-23 09:32 UTC
Labels: duplicate
